<a href="https://colab.research.google.com/github/ssp22/485Design-Project/blob/master/stream_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt

In [17]:
# 0 is water
# 1 is ethanol
# 2 is other components
# all units in grams

streamTable = np.zeros((8,3))
print(streamTable)

#set water in stream 1 to 10000 g
streamTable[0,0] = 10000
#set feed stream to membrane separator tanks to 
print(streamTable)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[10000.     0.     0.]
 [    0.     0.     0.]
 [    0.     0.     0.]
 [    0.     0.     0.]
 [    0.     0.     0.]
 [    0.     0.     0.]
 [    0.     0.     0.]
 [    0.     0.     0.]]
